# Generated by Django 3.2 on 2021-06-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
