# Generated by Django 3.2 on 2021-06-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='address_1',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='category',
            name='address_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='category',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='category',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
