# Generated by Django 3.2 on 2021-06-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20210607_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='city',
        ),
        migrations.RemoveField(
            model_name='category',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='category',
            name='state',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_1',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
