# Generated by Django 3.2 on 2021-06-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210607_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.SmallIntegerField(default=1000),
        ),
    ]
