# Generated by Django 3.2 on 2021-06-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_category_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ingredient',
            field=models.TextField(blank=True),
        ),
    ]
