# Generated by Django 3.2 on 2021-06-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20210615_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
