# Generated by Django 3.2 on 2021-06-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_menu_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.CharField(max_length=128),
        ),
    ]
